=== brandonsgh123127/assignment-2--databases--cs-365--fall-2020/xml/dtd/student.dtd
<!ELEMENT student (personalInfo+)>
        <!ATTLIST student
                format (full|part|graduate|withdrawn) #REQUIRED>

        <!ELEMENT personalInfo (creates)*>
        <!-- The id must always begin with a letter or underscore. -->
        <!ATTLIST personalInfo
                id ID #REQUIRED
                lname CDATA #REQUIRED
                fname CDATA #REQUIRED
                mname CDATA #REQUIRED
                prefname CDATA #IMPLIED
                email CDATA #REQUIRED
                phone CDATA #REQUIRED>

        <!ELEMENT creates (academicInfo+)>
        <!ATTLIST creates initEnrollment CDATA #REQUIRED>

        <!ELEMENT academicInfo (grades)+>
        <!ATTLIST academicInfo id ID #REQUIRED
                advisor CDATA #REQUIRED
                major CDATA #REQUIRED
                minor CDATA #IMPLIED
                expectedgrad CDATA #REQUIRED
                status CDATA #REQUIRED
                >
        <!ELEMENT grades (data)+>
        <!ATTLIST grades
                id ID #REQUIRED
                gpa CDATA #REQUIRED
                >
        <!ELEMENT data EMPTY>
        <!ATTLIST data year CDATA #REQUIRED
                semester CDATA #REQUIRED
                gpa CDATA #REQUIRED>

=== brandonsgh123127/assignment-2--databases--cs-365--fall-2020/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE student SYSTEM "dtd/student.dtd">
<?xml-stylesheet href="css/style.css"?>

<student format="full">
    <personalInfo lname="Spada" fname="Brandon" mname="R" email="sample@sample.com" phone="888-888-8888" id="a_1f">
        <creates initEnrollment="10/21/2016">
            <academicInfo advisor="Dr. Rosiene" expectedgrad="2020" major="Computer Science" status="Senior" id="alb_1">
                <grades gpa="3.49" id="g_19920">
                    <data year="2017" semester="Fall" gpa="4.00"/>
                    <data year="2018" semester="Spring" gpa="3.33"/>
                    <data year="2018" semester="Fall" gpa="3.66"/>
                </grades>
            </academicInfo>
        </creates>
    </personalInfo>
</student>
